### ISSUE TITLE
object 'comm' not found

### ISSUE THREAD

**Issue by karolinazarzyczny** [daijiang/hillR#11]
I'm trying to run the hillR code using the comm data within the package. I have installed and loaded the package but I get the notification that object "comm" is not found when I try to run the code. 

This is what I'm seeing:

> library(hillR)
> hill_taxa(comm, q = 0, MARGIN = 1, base = exp(1))
Error in as.matrix(comm) : object 'comm' not found

**Comment by daijiang** [comment]
Hi, `hillR` does not have data build in. You need to specify your own data like this: `hill_taxa(comm = FD::dummy$abun, q = 0)`.
