### ISSUE TITLE
R　session  abored

### ISSUE THREAD

**Issue by kobe-ball** [daijiang/hillR#20]
When the R code run the hill_phylo(comm, tree, q = 0) in version 0.5.1, the R studio is always in session aborted. although, I had tried from the R4.1.3 to R4.2.1, even re-install the R and the RStudio.  I am looking forward to getting your help to solve this problem, thank you!!!
![61bd77ae291a154837da86d8655296a](https://user-images.githubusercontent.com/52816385/195242359-0a28b351-788f-4780-a969-e6a506ef75f8.jpg)

**Comment by daijiang** [comment]
I am not sure about this since I cannot reproduce your problem. Maybe try to not use Rstudio? It is more like a Rstudio problem to me.
