### ISSUE TITLE
Installation instructions - dependencies

### ISSUE THREAD

**Issue by sydnerecord** [daijiang/hillR#7]
Currently the devtool option automates the dependencies, but for posterity it may be helpful to also list the dependencies and package version numbers in case there are ever issues with devtools.

**Comment by sydnerecord** [comment]
Please, also include package version numbers.

**Comment by daijiang** [comment]
Hi Sydne, if a package version number is missing in the DESCRIPTION, that means hillR works with any version of the packages imported.

**Comment by sydnerecord** [comment]
Hi Daijang, 
Agreed, but will that be the case in 10 years? Maybe safest to include the versions of dependencies, but I'll defer to the editors on this one.

**Comment by daijiang** [comment]
Hi Sydne,
I think the authors of the imported package will do reverse checking when they update their packages to CRAN. If their packages break hillR with the new updates, they will need to solve their packages. So, given that hillR works with these imported packages at this moment, I do not think this will be an issue in the future (at least, on my end).
Best,
Daijiang
