### ISSUE TITLE
Reference similar R packages

### ISSUE THREAD

**Issue by sydnerecord** [daijiang/hillR#8]
It would be good to reference prior R packages for taxonomic diversity (e.g., vegetarian and iNext).

**Comment by sydnerecord** [comment]
I don't see the refs, and I don't understand the namin gof the zzz file?

**Comment by daijiang** [comment]
The refs are here https://github.com/daijiang/hillR/blob/master/R/zzz.R#L5

zzz is a traditional/common file name to document the package (as a whole).

**Comment by sydnerecord** [comment]
Please, include the doi's and stick them in the bibliography.

**Comment by daijiang** [comment]
Both packages do not have a doi ... And I don't think it is appropriate to put them in the References given that hillR is not based on these packages.
