### ISSUE TITLE
error in `hill_taxa_parti` if sites have the same and only one species

### ISSUE THREAD

**Issue by FabianRoger** [daijiang/hillR#9]
M is a matrix with two sites that both have the same species and only one species in common.

```
M <- matrix(c(0,1,0,0,1,0), byrow = T, ncol = 3)
hill_taxa_parti(M)
```

if we try to calculate beta diversity for M we get the following error:

`Error in !all.equal(sum(comm_gamma), 1) : invalid argument type`

I suspect this occurs because `Some species in comm data were not observed in any site,
 delete them...` which likely reduces the matrix to a vector which might cause an error upstream which causes `sum(comm_gamma)` to give `NA` or `NULL`. This is, however, speculation as I haven't found which function calls this code (haven't dug deep though yet)

*edit*: forgot to say - thank you **so** much for this package it was thoroughly missing!

**Comment by daijiang** [comment]
Thanks! Now should be fixed.
